spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: nebula-service-auth
              uri: http://localhost:9001
              predicates:
                - Path=/auth/**
            - id: nebula-service-system
              uri: http://localhost:9002
              predicates:
                - Path=/system/**