spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: nebula-service-manager
              uri: http://${NEBULA_SERVICE_MANAGER_HOST:127.0.0.1}:${NEBULA_SERVICE_MANAGER_PORT:8081}
              predicates:
                - Path=/manager/**
            - id: nebula-service-blog
              uri: http://${NEBULA_SERVICE_BLOG_HOST:127.0.0.1}:${NEBULA_SERVICE_BLOG_PORT:8082}
              predicates:
                - Path=/blog/**
            - id: nebula-service-space
              uri: http://${NEBULA_SERVICE_SPACE_HOST:127.0.0.1}:${NEBULA_SERVICE_SPACE_PORT:8083}
              predicates:
                - Path=/space/**
