spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: nebula-service-manager
              uri: http://localhost:9001
              predicates:
                - Path=/auth/**,/manager/**
