server:
  port: 9001

spring:
  application:
    name: nebula-service-auth

sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
