server:
  port: 8082
  servlet:
    context-path: /blog

spring:
  application:
    name: nebula-service-blog
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://140.143.222.164:3307/flux_note?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: hump
    password: "hump!#123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 140.143.222.164
      port: 6380
      password: "hump!#123"
      database: 0
      timeout: 5s

nebula:
  redis:
    namespace: nebula

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: INFO
    com.nebula: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info