-- ============================================================
-- 流程图与 Agent 配置种子数据
--
-- 来源：docs/nebula.sql（开发环境导出）中的配置类数据。
-- 仅含画布上建立的编排图定义与 Agent 定义，刻意排除运行时记录
-- (ai_agent_instance / ai_flow_run / ai_harness_* / ai_flow_draft)，
-- 避免把开发环境的执行痕迹带进生产库。
--
-- 本文件由 .sqlmerge.py 生成，勿手工编辑。
-- ============================================================

SET NAMES utf8mb4;

-- nebula.sql 的种子里夹带了开发环境的运行记录（Agent 实例、状态转移、
-- 迭代链等）。留着会让 IterationDriver 的 heartbeat 反复去跑这些历史链条，
-- 在新环境里必然失败并刷满错误日志，故在此清空。
-- 注意只清运行记录，编排图与 Agent 定义属于配置，必须保留。
DELETE FROM `ai_agent_instance_transition`;
DELETE FROM `ai_agent_instance`;
DELETE FROM `ai_agent_iteration`;
DELETE FROM `ai_flow_run_node`;
DELETE FROM `ai_flow_run`;
DELETE FROM `ai_harness_confirmation`;
DELETE FROM `ai_harness_operation`;
DELETE FROM `ai_flow_draft`;

-- nebula.sql 里也有 blog_series 的旧版节点，且主键与此处不重叠。
-- 不先清掉会新旧并存导致流程图错乱，故本文件接管的流程整体重建。
DELETE FROM `ai_flow_edge` WHERE `flow_code` IN ('blog_series', 'daily_blog_creator', 'blog_outline_agent', 'daily_blog_generator', 'blog_generation');
DELETE FROM `ai_flow_node` WHERE `flow_code` IN ('blog_series', 'daily_blog_creator', 'blog_outline_agent', 'daily_blog_generator', 'blog_generation');
DELETE FROM `ai_flow`      WHERE `flow_code` IN ('blog_series', 'daily_blog_creator', 'blog_outline_agent', 'daily_blog_generator', 'blog_generation');

-- ---------- ai_flow (5 条) ----------
INSERT INTO `ai_flow` VALUES (5, 'blog_series', '博客系列生成', '按系列大纲逐篇生成博客，边写边规划', 1, 'DS-V3-001', 1, '2026-07-08 17:09:27', '2026-07-08 17:09:27', 'STATE_MACHINE', 100, 8, NULL);
INSERT INTO `ai_flow` VALUES (6, 'daily_blog_creator', '每日博客创作', '每天自动创建一个博客文章：获取今日信息→生成主题→撰写文章→润色优化→输出最终博客', 1, 'DS-V3-001', 1, '2026-07-23 20:16:11', '2026-07-23 20:16:11', 'DAG', 100, 8, NULL);
INSERT INTO `ai_flow` VALUES (7, 'blog_outline_agent', '博客目录生成 Agent', '根据用户提供的主题，自动生成带目录结构的完整博客文章', 1, 'DS-V3-001', 1, '2026-07-23 20:23:59', '2026-07-23 20:23:59', 'DAG', 100, 8, NULL);
INSERT INTO `ai_flow` VALUES (18, 'daily_blog_generator', '每日博客生成流程', '按天循环生成博客：每天先产出结构化大纲，再撰写完整正文，并经过内容检查确认，最终汇总为多篇可发布文章。', 1, 'DS-V3-001', 1, '2026-08-11 19:42:45', '2026-08-11 19:42:45', 'DAG', 100, 8, NULL);
INSERT INTO `ai_flow` VALUES (19, 'blog_generation', '博客生成流程', '根据用户提供的主题、风格和目标读者，自动生成完整博客文章：先规划提纲，再撰写初稿，最后润色优化。', 1, 'DS-V3-001', 1, '2026-08-11 20:31:33', '2026-08-11 20:31:33', 'DAG', 100, 8, NULL);

-- ---------- ai_flow_node (29 条) ----------
INSERT INTO `ai_flow_node` VALUES (118, 'blog_series', 'node_13', '', 'IF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"if\": {\"branches\": [{\"id\": \"br_5\", \"label\": \"分支1\", \"condition\": {\"logic\": \"AND\", \"clauses\": [{\"op\": \"eq\", \"left\": \"\", \"right\": \"\"}]}}, {\"id\": \"br_6\", \"label\": \"否则\", \"isElse\": true, \"condition\": {\"logic\": \"AND\", \"clauses\": [{\"op\": \"eq\", \"left\": \"\", \"right\": \"\"}]}}]}, \"__x6\": {\"x\": 199, \"y\": 25.109375}}', 0, 0, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (119, 'blog_series', 'node_4', '', 'AGENT_REACT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 580, \"y\": 50}}', 0, 1, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (120, 'blog_series', 'node_2', '写一篇并更新大纲', 'PROMPT', '你是一个技术博客连载作者。围绕系列主题《{{topic}}》持续创作。\n\n已有整体大纲：{{outline}}\n累积写作状态（已用例子/已讲知识点/风格）：{{accumulated}}\n已写文章索引：{{history}}\n这是第 {{prevSeq}} 篇之后的下一篇。\n\n请：\n1. 基于大纲与累积状态，决定并撰写下一篇文章（承接前文、不重复已讲内容）。\n2. 如有需要，微调整体大纲（边写边规划）。\n3. 更新累积写作状态。\n4. 判断系列是否已写完。\n\n只输出 JSON，无其它文字：', '请生成下一篇。', 'DS-V3-JSON-004', NULL, NULL, 'admin', NULL, 0.8, 4096, 1, NULL, NULL, NULL, NULL, 'seriesState', 'JSON', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-JSON-004\"}, \"output\": {\"type\": \"JSON\"}, \"prompt\": {\"systemPrompt\": \"你是一位资深 Java 工程师兼技术博主，擅长用可运行的代码示例讲解原理。行文简洁、避免空话，每个概念都配一段完整可编译的示例代码。\", \"userPromptCode\": \"BLOG_SERIES_OUTLINE\", \"systemPromptCode\": \"TECH_WRITER_PERSONA\", \"userPromptTemplate\": \"请围绕主题「{{topic}}」规划一个 {{count}} 篇的系列文章大纲，写作风格为 {{style}}。\\n每篇给出标题与一句话简介，输出 JSON 数组。\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 4096, \"temperature\": 0.7}}, \"__x6\": {\"x\": 390, \"y\": 230}}', 1, 2, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (121, 'blog_series', 'node_3', '结束', 'END', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 740, \"y\": 260}}', 0, 3, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'TERMINAL');
INSERT INTO `ai_flow_node` VALUES (122, 'blog_series', 'node_1', '开始', 'START', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 40, \"y\": 260}, \"inputs\": {\"topic\": \"系列主题\", \"history\": \"已写文章索引\", \"outline\": \"上一轮大纲\", \"prevSeq\": \"上一篇序号\", \"accumulated\": \"累积状态\"}}', 0, 4, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'ENTRY');
INSERT INTO `ai_flow_node` VALUES (123, 'blog_series', 'node_5', '博客系列生成', 'AGENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 350, \"y\": 390}, \"inputMapping\": {}, \"refAgentCode\": \"blog_series\", \"outputMapping\": {}, \"__agentRefName\": \"博客系列生成\"}', 0, 5, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (124, 'blog_series', 'node_12', '', 'AGENT_REACT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 40, \"y\": 424.109375}}', 0, 6, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (125, 'blog_series', 'node_10', '', 'IF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"if\": {\"branches\": [{\"id\": \"br_1\", \"label\": \"分支1\", \"condition\": {\"logic\": \"AND\", \"clauses\": [{\"op\": \"eq\", \"left\": \"\", \"right\": \"\"}]}}, {\"id\": \"br_2\", \"label\": \"否则\", \"isElse\": true, \"condition\": {\"logic\": \"AND\", \"clauses\": [{\"op\": \"eq\", \"left\": \"\", \"right\": \"\"}]}}]}, \"__x6\": {\"x\": 640, \"y\": 520.109375}}', 0, 7, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (126, 'blog_series', 'node_9', '', 'JOIN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 199, \"y\": 530.109375}}', 0, 8, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (127, 'blog_series', 'node_11', '', 'TOOL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 358, \"y\": 702.109375}}', 0, 9, '2026-07-21 16:23:17', '2026-07-21 16:23:17', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (128, 'daily_blog_creator', 'start', '开始', 'START', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 120.0, \"y\": 200.0}}', 0, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_node` VALUES (129, 'daily_blog_creator', 'get_topic', '获取主题灵感', 'PROMPT', NULL, '今天是 #{date}。请根据当前热门趋势和时事，构思一个有趣、有深度且适合博客发布的主题。\n要求：主题要新颖，有吸引力，适合大众阅读。\n请直接输出一个博客主题标题（20字以内）。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'topic', 'TEXT', '{\"__x6\": {\"x\": 360.0, \"y\": 200.0}}', 0, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_node` VALUES (130, 'daily_blog_creator', 'write_blog', '撰写博客正文', 'PROMPT', NULL, '请根据以下博客主题，撰写一篇完整的博客文章。\n\n主题：#{topic}\n\n要求：\n1. 文章结构完整，包含引言、正文（2-3个小节）、结语\n2. 语言生动有趣，通俗易懂\n3. 字数在800-1200字之间\n4. 适当使用小标题、列表等格式\n5. 文章风格积极向上，有深度思考\n\n请直接输出完整的博客文章。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'draft', 'TEXT', '{\"__x6\": {\"x\": 600.0, \"y\": 200.0}}', 0, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_node` VALUES (131, 'daily_blog_creator', 'polish', '润色优化', 'PROMPT', NULL, '请对以下博客文章进行润色优化，使其更具可读性和吸引力。\n\n原文：\n#{draft}\n\n润色要求：\n1. 修正语法和表达问题\n2. 优化段落衔接，使行文更流畅\n3. 增强标题的吸引力\n4. 保持原文的核心观点和风格\n5. 添加一个简短的摘要（50字以内）放在文章最前面\n\n请直接输出润色后的完整博客文章，摘要用【摘要】标记。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'final_blog', 'TEXT', '{\"__x6\": {\"x\": 840.0, \"y\": 200.0}}', 0, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_node` VALUES (132, 'daily_blog_creator', 'end', '结束', 'END', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 1080.0, \"y\": 200.0}}', 0, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_node` VALUES (137, 'blog_outline_agent', 'start', '开始', 'START', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 120, \"y\": 200}}', 0, 0, '2026-07-23 20:24:25', '2026-07-23 20:24:25', 'ENTRY');
INSERT INTO `ai_flow_node` VALUES (138, 'blog_outline_agent', 'generate_outline', '生成目录', 'PROMPT', '你是一位专业的博客写手，擅长为各类主题规划清晰、有吸引力的文章结构。', '请根据以下博客主题，生成一篇结构清晰的目录大纲。\n\n主题：#{topic}\n\n要求：\n1. 目录层级不超过3级\n2. 包含引言、正文（2-4个章节）、结语\n3. 每个章节给出核心要点\n4. 用 Markdown 格式输出\n\n目录大纲：', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'outline', 'TEXT', '{\"__x6\": {\"x\": 360, \"y\": 200}}', 0, 1, '2026-07-23 20:24:25', '2026-07-23 20:24:25', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (139, 'blog_outline_agent', 'generate_content', '生成正文', 'PROMPT', '你是一位资深博客作者，文笔生动流畅，逻辑清晰，擅长将目录大纲扩展为完整的博客文章。', '请根据以下目录大纲，展开撰写一篇完整的博客文章。\n\n主题：#{topic}\n\n目录大纲：\n#{outline}\n\n要求：\n1. 严格按照目录结构展开，每个章节内容充实\n2. 语言生动自然，贴近读者\n3. 全文不少于800字\n4. 用 Markdown 格式输出，包含标题层级（#, ##, ###）\n\n完整博客文章：', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'blogContent', 'TEXT', '{\"__x6\": {\"x\": 600, \"y\": 200}}', 0, 2, '2026-07-23 20:24:25', '2026-07-23 20:24:25', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (140, 'blog_outline_agent', 'end', '结束', 'END', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 840, \"y\": 200}}', 0, 3, '2026-07-23 20:24:25', '2026-07-23 20:24:25', 'TERMINAL');
INSERT INTO `ai_flow_node` VALUES (163, 'daily_blog_generator', 'start', '开始', 'START', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 120, \"y\": 80}, \"inputs\": {\"days\": {\"type\": \"integer\", \"description\": \"需要生成博客的天数，每天一篇\"}, \"tone\": {\"type\": \"string\", \"description\": \"写作语气，默认专业\"}, \"topic\": {\"type\": \"string\", \"description\": \"博客主题\"}, \"audience\": {\"type\": \"string\", \"description\": \"目标受众\"}, \"language\": {\"type\": \"string\", \"description\": \"目标语言，默认中文\"}}}', 0, 0, '2026-08-11 19:49:06', '2026-08-11 19:49:06', 'ENTRY');
INSERT INTO `ai_flow_node` VALUES (164, 'daily_blog_generator', 'gen_outline', '生成博客大纲', 'PROMPT', '你是一位资深内容策划与博客写作专家，擅长为主题搭建结构清晰、逻辑严谨的博客大纲。你输出的内容必须严格遵循指定的 JSON 格式，不输出任何多余文字。', '请为主题「{{topic}}」设计一篇博客文章的完整大纲。\n\n要求：\n- 目标语言：{{language}}\n- 目标受众：{{audience}}\n- 写作语气：{{tone}}\n\n大纲需包含：引言要点、3-5 个主体章节（每章给出核心论点与要点）、结论要点。\n\n请只输出 JSON，格式如下：\n{\n  \"title\": \"建议的博客标题\",\n  \"introduction_points\": [\"要点1\", \"要点2\"],\n  \"sections\": [\n    {\"heading\": \"章节标题\", \"key_points\": [\"要点1\", \"要点2\"]}\n  ],\n  \"conclusion_points\": [\"要点1\", \"要点2\"]\n}', 'DS-V3-JSON-004', NULL, NULL, NULL, NULL, 0.3, 1500, 1, NULL, NULL, NULL, NULL, 'outline', 'JSON', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-JSON-004\"}, \"output\": {\"type\": \"JSON\"}, \"prompt\": {\"systemPrompt\": \"你是一位资深内容策划与博客写作专家，擅长为主题搭建结构清晰、逻辑严谨的博客大纲。你输出的内容必须严格遵循指定的 JSON 格式，不输出任何多余文字。\", \"userPromptCode\": \"\", \"systemPromptCode\": \"\", \"userPromptTemplate\": \"请为主题「{{topic}}」设计一篇博客文章的完整大纲。\\n\\n要求：\\n- 目标语言：{{language}}\\n- 目标受众：{{audience}}\\n- 写作语气：{{tone}}\\n\\n大纲需包含：引言要点、3-5 个主体章节（每章给出核心论点与要点）、结论要点。\\n\\n请只输出 JSON，格式如下：\\n{\\n  \\\"title\\\": \\\"建议的博客标题\\\",\\n  \\\"introduction_points\\\": [\\\"要点1\\\", \\\"要点2\\\"],\\n  \\\"sections\\\": [\\n    {\\\"heading\\\": \\\"章节标题\\\", \\\"key_points\\\": [\\\"要点1\\\", \\\"要点2\\\"]}\\n  ],\\n  \\\"conclusion_points\\\": [\\\"要点1\\\", \\\"要点2\\\"]\\n}\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 1500, \"temperature\": 0.3}}, \"__x6\": {\"x\": 360, \"y\": 80}}', 0, 1, '2026-08-11 19:49:06', '2026-08-11 19:49:06', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (165, 'daily_blog_generator', 'write_article', '撰写博客正文', 'PROMPT', '你是一位专业的博客作者，擅长把结构化大纲扩展为流畅、有深度、可读性强的完整文章。请严格按照大纲组织内容，保持语气一致，输出自然连贯的正文。', '请根据以下大纲撰写一篇完整博客正文。\n\n【博客主题】{{topic}}\n【目标语言】{{language}}\n【目标受众】{{audience}}\n【写作语气】{{tone}}\n\n【大纲内容】\n{{outline}}\n\n要求：\n1. 标题采用大纲中的建议标题。\n2. 按大纲的章节顺序展开，每个章节围绕核心论点充分论述。\n3. 正文需包含引言、主体和结论，整体篇幅完整充实。\n4. 语气贴合目标受众，语言使用{{language}}。\n5. 请只输出正文内容本身，不要输出 JSON 或额外说明。', 'DS-V3-CREATIVE-003', NULL, NULL, NULL, NULL, 0.7, 4000, 1, NULL, NULL, NULL, NULL, 'article', 'TEXT', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-CREATIVE-003\"}, \"output\": {\"type\": \"TEXT\"}, \"prompt\": {\"systemPrompt\": \"你是一位专业的博客作者，擅长把结构化大纲扩展为流畅、有深度、可读性强的完整文章。请严格按照大纲组织内容，保持语气一致，输出自然连贯的正文。\", \"userPromptCode\": \"\", \"systemPromptCode\": \"\", \"userPromptTemplate\": \"请根据以下大纲撰写一篇完整博客正文。\\n\\n【博客主题】{{topic}}\\n【目标语言】{{language}}\\n【目标受众】{{audience}}\\n【写作语气】{{tone}}\\n\\n【大纲内容】\\n{{outline}}\\n\\n要求：\\n1. 标题采用大纲中的建议标题。\\n2. 按大纲的章节顺序展开，每个章节围绕核心论点充分论述。\\n3. 正文需包含引言、主体和结论，整体篇幅完整充实。\\n4. 语气贴合目标受众，语言使用{{language}}。\\n5. 请只输出正文内容本身，不要输出 JSON 或额外说明。\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 4000, \"temperature\": 0.7}}, \"__x6\": {\"x\": 600, \"y\": 80}}', 0, 2, '2026-08-11 19:49:06', '2026-08-11 19:49:06', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (166, 'daily_blog_generator', 'end', '结束', 'END', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"end\": {\"outputJson\": {\"days\": \"{{days}}\", \"topic\": \"{{topic}}\", \"articles\": \"{{daily_loop.outputs}}\"}}, \"__x6\": {\"x\": 120, \"y\": 220}}', 0, 3, '2026-08-11 19:49:06', '2026-08-11 19:49:06', 'TERMINAL');
INSERT INTO `ai_flow_node` VALUES (167, 'daily_blog_generator', 'check_content', '确认博客内容检查', 'PROMPT', '你是一位严谨的博客内容审核专家，负责对生成的博客正文进行质量检查。你只输出符合指定 JSON 格式的检查结论，不输出任何多余文字。', '请对以下博客正文做一次内容质量检查，并给出确认结论。\n\n【博客主题】{{topic}}\n【目标语言】{{language}}\n【目标受众】{{audience}}\n【写作语气】{{tone}}\n\n【博客大纲】\n{{outline}}\n\n【博客正文】\n{{article}}\n\n请从以下维度检查并只输出 JSON：\n1. 完整性：正文是否包含引言、主体章节、结论，是否覆盖大纲所有要点；\n2. 一致性：内容是否与主题、大纲一致，语气是否贴合受众；\n3. 质量：是否存在明显语病、逻辑断裂或空泛表述；\n4. 语言：是否使用目标语言{{language}}。\n\n输出格式：\n{\n  \"passed\": true 或 false,\n  \"score\": 0-100 的整数评分,\n  \"issues\": [\"发现的问题，若无则为空数组\"],\n  \"suggestions\": [\"改进建议，若无则为空数组\"],\n  \"confirmation\": \"确认通过\" 或 \"需要修订\"\n}', 'DS-V3-JSON-004', NULL, NULL, NULL, NULL, 0.2, 1000, 1, NULL, NULL, NULL, NULL, 'check_result', 'JSON', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-JSON-004\"}, \"output\": {\"type\": \"JSON\"}, \"prompt\": {\"systemPrompt\": \"你是一位严谨的博客内容审核专家，负责对生成的博客正文进行质量检查。你只输出符合指定 JSON 格式的检查结论，不输出任何多余文字。\", \"userPromptCode\": \"\", \"systemPromptCode\": \"\", \"userPromptTemplate\": \"请对以下博客正文做一次内容质量检查，并给出确认结论。\\n\\n【博客主题】{{topic}}\\n【目标语言】{{language}}\\n【目标受众】{{audience}}\\n【写作语气】{{tone}}\\n\\n【博客大纲】\\n{{outline}}\\n\\n【博客正文】\\n{{article}}\\n\\n请从以下维度检查并只输出 JSON：\\n1. 完整性：正文是否包含引言、主体章节、结论，是否覆盖大纲所有要点；\\n2. 一致性：内容是否与主题、大纲一致，语气是否贴合受众；\\n3. 质量：是否存在明显语病、逻辑断裂或空泛表述；\\n4. 语言：是否使用目标语言{{language}}。\\n\\n输出格式：\\n{\\n  \\\"passed\\\": true 或 false,\\n  \\\"score\\\": 0-100 的整数评分,\\n  \\\"issues\\\": [\\\"发现的问题，若无则为空数组\\\"],\\n  \\\"suggestions\\\": [\\\"改进建议，若无则为空数组\\\"],\\n  \\\"confirmation\\\": \\\"确认通过\\\" 或 \\\"需要修订\\\"\\n}\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 1000, \"temperature\": 0.2}}, \"__x6\": {\"x\": 360, \"y\": 220}}', 0, 4, '2026-08-11 19:49:06', '2026-08-11 19:49:06', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (168, 'blog_generation', 'start', '开始', 'START', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"__x6\": {\"x\": 120, \"y\": 80}, \"inputs\": [{\"name\": \"topic\", \"type\": \"string\", \"example\": \"如何高效使用 AI 辅助写作\", \"required\": true, \"description\": \"博客文章的主题\"}, {\"name\": \"style\", \"type\": \"string\", \"example\": \"轻松易懂\", \"required\": false, \"description\": \"写作风格，如专业、轻松、幽默等\"}, {\"name\": \"targetAudience\", \"type\": \"string\", \"example\": \"希望提升写作效率的职场人士\", \"required\": false, \"description\": \"目标读者群体\"}, {\"name\": \"wordCount\", \"type\": \"integer\", \"example\": 1500, \"required\": false, \"description\": \"期望的文章字数\", \"defaultValue\": 1500}]}', 0, 0, '2026-08-11 20:31:33', '2026-08-11 20:31:33', 'ENTRY');
INSERT INTO `ai_flow_node` VALUES (169, 'blog_generation', 'outline_gen', '生成文章提纲', 'PROMPT', '你是一位资深的博客内容策划专家，擅长为不同主题和读者规划清晰、有吸引力的文章结构。你输出的提纲逻辑严密、层次分明，能引导读者循序渐进地理解主题。', '请为主题「{{topic}}」规划一篇博客文章的详细提纲。\n\n写作风格：{{#style}}{{style}}{{/style}}{{^style}}专业清晰{{/style}}\n目标读者：{{#targetAudience}}{{targetAudience}}{{/targetAudience}}{{^targetAudience}}普通读者{{/targetAudience}}\n期望字数：约 {{wordCount}} 字\n\n请输出一个 JSON 对象，包含以下字段：\n{\n  \"title\": \"建议的文章标题（吸引眼球）\",\n  \"sections\": [\n    {\"heading\": \"章节标题\", \"points\": [\"要点1\", \"要点2\"]}\n  ],\n  \"keyTakeaways\": [\"读者读完应收获的核心要点\"]\n}\n\n只输出 JSON，不要有任何额外文字。', 'DS-V3-JSON-004', NULL, NULL, NULL, NULL, 0.7, 1000, 1, NULL, NULL, NULL, NULL, 'outline', 'JSON', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-JSON-004\"}, \"output\": {\"type\": \"JSON\"}, \"prompt\": {\"systemPrompt\": \"你是一位资深的博客内容策划专家，擅长为不同主题和读者规划清晰、有吸引力的文章结构。你输出的提纲逻辑严密、层次分明，能引导读者循序渐进地理解主题。\", \"userPromptCode\": \"\", \"systemPromptCode\": \"\", \"userPromptTemplate\": \"请为主题「{{topic}}」规划一篇博客文章的详细提纲。\\n\\n写作风格：{{#style}}{{style}}{{/style}}{{^style}}专业清晰{{/style}}\\n目标读者：{{#targetAudience}}{{targetAudience}}{{/targetAudience}}{{^targetAudience}}普通读者{{/targetAudience}}\\n期望字数：约 {{wordCount}} 字\\n\\n请输出一个 JSON 对象，包含以下字段：\\n{\\n  \\\"title\\\": \\\"建议的文章标题（吸引眼球）\\\",\\n  \\\"sections\\\": [\\n    {\\\"heading\\\": \\\"章节标题\\\", \\\"points\\\": [\\\"要点1\\\", \\\"要点2\\\"]}\\n  ],\\n  \\\"keyTakeaways\\\": [\\\"读者读完应收获的核心要点\\\"]\\n}\\n\\n只输出 JSON，不要有任何额外文字。\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 1000, \"temperature\": 0.7}}, \"__x6\": {\"x\": 500, \"y\": 80}}', 0, 1, '2026-08-11 20:31:33', '2026-08-11 20:31:33', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (170, 'blog_generation', 'draft_write', '撰写初稿', 'PROMPT', '你是一位才华横溢的博客写手，文笔流畅、表达生动。你能按照提纲把主题展开成一篇完整、连贯、有吸引力的文章，让读者愿意读下去并有所收获。', '请根据以下提纲撰写一篇完整的博客文章初稿。\n\n文章主题：{{topic}}\n写作风格：{{#style}}{{style}}{{/style}}{{^style}}专业清晰{{/style}}\n目标读者：{{#targetAudience}}{{targetAudience}}{{/targetAudience}}{{^targetAudience}}普通读者{{/targetAudience}}\n期望字数：约 {{wordCount}} 字\n\n提纲内容：\n{{outline}}\n\n请根据提纲展开，写出完整的文章正文（包含标题、引言、各章节内容、结论）。语言要自然流畅，符合指定的写作风格和读者群体。请确保字数接近期望值。\n\n直接输出文章正文（Markdown 格式），不要输出 JSON。', 'DS-V3-CREATIVE-003', NULL, NULL, NULL, NULL, 0.8, 3000, 1, NULL, NULL, NULL, NULL, 'draft', 'TEXT', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-CREATIVE-003\"}, \"output\": {\"type\": \"TEXT\"}, \"prompt\": {\"systemPrompt\": \"你是一位才华横溢的博客写手，文笔流畅、表达生动。你能按照提纲把主题展开成一篇完整、连贯、有吸引力的文章，让读者愿意读下去并有所收获。\", \"userPromptCode\": \"\", \"systemPromptCode\": \"\", \"userPromptTemplate\": \"请根据以下提纲撰写一篇完整的博客文章初稿。\\n\\n文章主题：{{topic}}\\n写作风格：{{#style}}{{style}}{{/style}}{{^style}}专业清晰{{/style}}\\n目标读者：{{#targetAudience}}{{targetAudience}}{{/targetAudience}}{{^targetAudience}}普通读者{{/targetAudience}}\\n期望字数：约 {{wordCount}} 字\\n\\n提纲内容：\\n{{outline}}\\n\\n请根据提纲展开，写出完整的文章正文（包含标题、引言、各章节内容、结论）。语言要自然流畅，符合指定的写作风格和读者群体。请确保字数接近期望值。\\n\\n直接输出文章正文（Markdown 格式），不要输出 JSON。\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 3000, \"temperature\": 0.8}}, \"__x6\": {\"x\": 880, \"y\": 80}}', 0, 2, '2026-08-11 20:31:33', '2026-08-11 20:31:33', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (171, 'blog_generation', 'polish', '润色优化', 'PROMPT', '你是一位精益求精的文字编辑，注重语言的准确、流畅与感染力。你擅长打磨文章，使表达更精炼、结构更清晰、逻辑更严密，同时保持原文的风格与核心内容不变。', '请对下面的博客文章初稿进行润色优化，使其达到最佳质量。\n\n原始主题：{{topic}}\n目标读者：{{targetAudience}}\n期望风格：{{#style}}{{style}}{{/style}}{{^style}}专业清晰{{/style}}\n\n初稿内容：\n{{draft}}\n\n润色要求：\n1. 修正语法错误、错别字和不通顺的句子\n2. 优化表达，使语言更精炼、生动\n3. 增强段落间的衔接与过渡，保证行文流畅\n4. 保持原文结构和核心内容不变\n5. 确保风格符合目标读者和期望风格\n\n直接输出润色后的完整文章（Markdown 格式），不要输出任何额外说明。', 'DS-V3-001', NULL, NULL, NULL, NULL, 0.5, 3000, 1, NULL, NULL, NULL, NULL, 'polished', 'TEXT', '{\"llm\": {\"model\": {\"profileCode\": \"DS-V3-001\"}, \"output\": {\"type\": \"TEXT\"}, \"prompt\": {\"systemPrompt\": \"你是一位精益求精的文字编辑，注重语言的准确、流畅与感染力。你擅长打磨文章，使表达更精炼、结构更清晰、逻辑更严密，同时保持原文的风格与核心内容不变。\", \"userPromptCode\": \"\", \"systemPromptCode\": \"\", \"userPromptTemplate\": \"请对下面的博客文章初稿进行润色优化，使其达到最佳质量。\\n\\n原始主题：{{topic}}\\n目标读者：{{targetAudience}}\\n期望风格：{{#style}}{{style}}{{/style}}{{^style}}专业清晰{{/style}}\\n\\n初稿内容：\\n{{draft}}\\n\\n润色要求：\\n1. 修正语法错误、错别字和不通顺的句子\\n2. 优化表达，使语言更精炼、生动\\n3. 增强段落间的衔接与过渡，保证行文流畅\\n4. 保持原文结构和核心内容不变\\n5. 确保风格符合目标读者和期望风格\\n\\n直接输出润色后的完整文章（Markdown 格式），不要输出任何额外说明。\"}, \"context\": {\"memory\": true, \"messages\": true, \"artifacts\": false, \"knowledge\": true, \"variables\": true}, \"parameters\": {\"seed\": null, \"topP\": 1, \"stream\": true, \"maxTokens\": 3000, \"temperature\": 0.5}}, \"__x6\": {\"x\": 120, \"y\": 272}}', 0, 3, '2026-08-11 20:31:33', '2026-08-11 20:31:33', 'NORMAL');
INSERT INTO `ai_flow_node` VALUES (172, 'blog_generation', 'end', '结束', 'END', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TEXT', '{\"end\": {\"outputJson\": {\"topic\": \"{{topic}}\", \"article\": \"{{polished}}\", \"outline\": \"{{outline}}\"}}, \"__x6\": {\"x\": 500, \"y\": 272}}', 0, 4, '2026-08-11 20:31:33', '2026-08-11 20:31:33', 'TERMINAL');

-- ---------- ai_flow_edge (18 条) ----------
INSERT INTO `ai_flow_edge` VALUES (51, 'blog_series', 'node_1', 'node_2', NULL, 0, '2026-07-21 16:23:17', '2026-07-21 16:23:17', NULL);
INSERT INTO `ai_flow_edge` VALUES (52, 'blog_series', 'node_2', 'node_3', NULL, 1, '2026-07-21 16:23:17', '2026-07-21 16:23:17', NULL);
INSERT INTO `ai_flow_edge` VALUES (53, 'daily_blog_creator', 'start', 'get_topic', NULL, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_edge` VALUES (54, 'daily_blog_creator', 'get_topic', 'write_blog', NULL, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_edge` VALUES (55, 'daily_blog_creator', 'write_blog', 'polish', NULL, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_edge` VALUES (56, 'daily_blog_creator', 'polish', 'end', NULL, 0, '2026-07-23 20:16:11', '2026-07-23 20:16:11', NULL);
INSERT INTO `ai_flow_edge` VALUES (60, 'blog_outline_agent', 'start', 'generate_outline', NULL, 0, '2026-07-23 20:24:25', '2026-07-23 20:24:25', NULL);
INSERT INTO `ai_flow_edge` VALUES (61, 'blog_outline_agent', 'generate_outline', 'generate_content', NULL, 1, '2026-07-23 20:24:25', '2026-07-23 20:24:25', NULL);
INSERT INTO `ai_flow_edge` VALUES (62, 'blog_outline_agent', 'generate_content', 'end', NULL, 2, '2026-07-23 20:24:25', '2026-07-23 20:24:25', NULL);
INSERT INTO `ai_flow_edge` VALUES (76, 'daily_blog_generator', 'gen_outline', 'write_article', NULL, 0, '2026-08-11 19:49:06', '2026-08-11 19:49:06', NULL);
INSERT INTO `ai_flow_edge` VALUES (77, 'daily_blog_generator', 'write_article', 'check_content', NULL, 1, '2026-08-11 19:49:06', '2026-08-11 19:49:06', NULL);
INSERT INTO `ai_flow_edge` VALUES (78, 'daily_blog_generator', 'daily_loop', 'end', NULL, 2, '2026-08-11 19:49:06', '2026-08-11 19:49:06', NULL);
INSERT INTO `ai_flow_edge` VALUES (79, 'daily_blog_generator', 'start', 'gen_outline', NULL, 3, '2026-08-11 19:49:06', '2026-08-11 19:49:06', NULL);
INSERT INTO `ai_flow_edge` VALUES (80, 'daily_blog_generator', 'check_content', 'daily_loop', NULL, 4, '2026-08-11 19:49:06', '2026-08-11 19:49:06', NULL);
INSERT INTO `ai_flow_edge` VALUES (81, 'blog_generation', 'start', 'outline_gen', NULL, 0, '2026-08-11 20:31:33', '2026-08-11 20:31:33', NULL);
INSERT INTO `ai_flow_edge` VALUES (82, 'blog_generation', 'outline_gen', 'draft_write', NULL, 1, '2026-08-11 20:31:33', '2026-08-11 20:31:33', NULL);
INSERT INTO `ai_flow_edge` VALUES (83, 'blog_generation', 'draft_write', 'polish', NULL, 2, '2026-08-11 20:31:33', '2026-08-11 20:31:33', NULL);
INSERT INTO `ai_flow_edge` VALUES (84, 'blog_generation', 'polish', 'end', NULL, 3, '2026-08-11 20:31:33', '2026-08-11 20:31:33', NULL);

-- ---------- ai_agent (1 条) ----------
INSERT INTO `ai_agent` VALUES (8, 'blog_outline_agent', '博客目录生成 Agent', '根据用户提供的主题，自动生成带目录结构的完整博客文章', 'blog_outline_agent', 1, '{\"type\":\"object\",\"required\":[\"topic\"],\"properties\":{\"topic\":{\"type\":\"string\",\"description\":\"博客主题\"}}}', '{\"type\":\"object\",\"properties\":{\"outline\":{\"type\":\"string\",\"description\":\"目录大纲\"},\"blogContent\":{\"type\":\"string\",\"description\":\"完整博客正文\"}}}', NULL, NULL, NULL, 1, 1, '2026-07-23 20:24:01', '2026-07-23 20:24:01');

