CREATE TABLE `space_bookmark_folder` (
                                         `id` bigint NOT NULL AUTO_INCREMENT COMMENT '目录ID',
                                         `user_id` bigint NOT NULL COMMENT '所属用户ID',
                                         `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父目录ID，0表示根目录',
                                         `ancestors` varchar(1000) NOT NULL DEFAULT '0' COMMENT '祖级列表，如0,1,2',
                                         `name` varchar(100) NOT NULL COMMENT '目录名称',
                                         `level` int NOT NULL DEFAULT '1' COMMENT '目录层级',
                                         `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
                                         `source` varchar(32) NOT NULL DEFAULT 'manual' COMMENT '来源：manual/chrome/import',
                                         `source_key` varchar(255) DEFAULT NULL COMMENT '外部来源标识',
                                         `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                         `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                                         `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         `update_by` bigint DEFAULT NULL,
                                         `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                         `deleted` tinyint NOT NULL DEFAULT '0',
                                         `delete_time` datetime DEFAULT NULL,
                                         PRIMARY KEY (`id`),
                                         KEY `idx_space_bookmark_folder_user_parent` (`user_id`, `parent_id`, `deleted`),
                                         KEY `idx_space_bookmark_folder_user_sort` (`user_id`, `sort_order`),
                                         KEY `idx_space_bookmark_folder_ancestors` (`ancestors`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='书签目录表';

CREATE TABLE `space_bookmark` (
                                  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '书签ID',
                                  `user_id` bigint NOT NULL COMMENT '所属用户ID',
                                  `folder_id` bigint NOT NULL DEFAULT '0' COMMENT '所属目录ID，0表示未分类',
                                  `title` varchar(500) NOT NULL COMMENT '书签标题',
                                  `url` text NOT NULL COMMENT '原始URL',
                                  `normalized_url` text COMMENT '规范化URL，用于去重',
                                  `url_hash` char(64) NOT NULL COMMENT 'URL哈希，用于索引和去重',
                                  `domain` varchar(255) DEFAULT NULL COMMENT '域名',
                                  `description` varchar(1000) DEFAULT NULL COMMENT '描述',
                                  `favicon_url` varchar(1000) DEFAULT NULL COMMENT '站点图标URL',
                                  `favicon_file_id` bigint DEFAULT NULL COMMENT '站点图标文件ID，关联sys_file',
                                  `source` varchar(32) NOT NULL DEFAULT 'manual' COMMENT '来源：manual/chrome/import',
                                  `source_key` varchar(255) DEFAULT NULL COMMENT '外部来源标识',
                                  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0正常 1归档 2失效',
                                  `visit_count` int NOT NULL DEFAULT '0' COMMENT '访问次数',
                                  `last_visit_time` datetime DEFAULT NULL COMMENT '最后访问时间',
                                  `sort_order` int NOT NULL DEFAULT '0' COMMENT '目录内排序',
                                  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                                  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  `update_by` bigint DEFAULT NULL,
                                  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                  `deleted` tinyint NOT NULL DEFAULT '0',
                                  `delete_time` datetime DEFAULT NULL,
                                  PRIMARY KEY (`id`),
                                  KEY `idx_space_bookmark_user_folder` (`user_id`, `folder_id`, `deleted`),
                                  KEY `idx_space_bookmark_user_hash` (`user_id`, `url_hash`, `deleted`),
                                  KEY `idx_space_bookmark_domain` (`domain`),
                                  KEY `idx_space_bookmark_status` (`user_id`, `status`, `deleted`),
                                  KEY `idx_space_bookmark_sort` (`folder_id`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='书签表';

CREATE TABLE `space_tag` (
                             `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标签ID',
                             `user_id` bigint NOT NULL COMMENT '所属用户ID',
                             `name` varchar(100) NOT NULL COMMENT '标签名称',
                             `color` varchar(32) DEFAULT NULL COMMENT '标签颜色',
                             `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
                             `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                             `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                             `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             `update_by` bigint DEFAULT NULL,
                             `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                             `deleted` tinyint NOT NULL DEFAULT '0',
                             `delete_time` datetime DEFAULT NULL,
                             PRIMARY KEY (`id`),
                             KEY `idx_space_tag_user_name` (`user_id`, `name`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='空间标签表';

CREATE TABLE `space_bookmark_tag` (
                                      `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                      `bookmark_id` bigint NOT NULL COMMENT '书签ID',
                                      `tag_id` bigint NOT NULL COMMENT '标签ID',
                                      `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                                      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      `update_by` bigint DEFAULT NULL,
                                      `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                      `deleted` tinyint NOT NULL DEFAULT '0',
                                      `delete_time` datetime DEFAULT NULL,
                                      PRIMARY KEY (`id`),
                                      KEY `idx_space_bookmark_tag_bookmark` (`bookmark_id`, `deleted`),
                                      KEY `idx_space_bookmark_tag_tag` (`tag_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='书签标签关联表';

CREATE TABLE `space_bookmark_import_task` (
                                              `id` bigint NOT NULL AUTO_INCREMENT COMMENT '导入任务ID',
                                              `user_id` bigint NOT NULL COMMENT '用户ID',
                                              `file_id` bigint DEFAULT NULL COMMENT '导入文件ID，关联sys_file',
                                              `source` varchar(32) NOT NULL DEFAULT 'chrome' COMMENT '来源：chrome/html/json',
                                              `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0待处理 1处理中 2成功 3失败',
                                              `total_count` int NOT NULL DEFAULT '0' COMMENT '总数量',
                                              `success_count` int NOT NULL DEFAULT '0' COMMENT '成功数量',
                                              `duplicate_count` int NOT NULL DEFAULT '0' COMMENT '重复数量',
                                              `fail_count` int NOT NULL DEFAULT '0' COMMENT '失败数量',
                                              `error_msg` varchar(2000) DEFAULT NULL COMMENT '错误信息',
                                              `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                                              `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              `update_by` bigint DEFAULT NULL,
                                              `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                              `deleted` tinyint NOT NULL DEFAULT '0',
                                              `delete_time` datetime DEFAULT NULL,
                                              PRIMARY KEY (`id`),
                                              KEY `idx_space_bookmark_import_task_user` (`user_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='书签导入任务表';

CREATE TABLE `space_bookmark_export_task` (
                                              `id` bigint NOT NULL AUTO_INCREMENT COMMENT '导出任务ID',
                                              `user_id` bigint NOT NULL COMMENT '用户ID',
                                              `file_id` bigint DEFAULT NULL COMMENT '导出文件ID，关联sys_file',
                                              `export_type` varchar(32) NOT NULL DEFAULT 'chrome_html' COMMENT '导出类型：chrome_html/json',
                                              `scope_type` varchar(32) NOT NULL DEFAULT 'all' COMMENT '范围：all/folder/tag',
                                              `scope_id` bigint DEFAULT NULL COMMENT '范围ID',
                                              `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0待处理 1处理中 2成功 3失败',
                                              `total_count` int NOT NULL DEFAULT '0' COMMENT '导出数量',
                                              `error_msg` varchar(2000) DEFAULT NULL COMMENT '错误信息',
                                              `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
                                              `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              `update_by` bigint DEFAULT NULL,
                                              `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                              `deleted` tinyint NOT NULL DEFAULT '0',
                                              `delete_time` datetime DEFAULT NULL,
                                              PRIMARY KEY (`id`),
                                              KEY `idx_space_bookmark_export_task_user` (`user_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='书签导出任务表';