CREATE TABLE IF NOT EXISTS `ai_harness_confirmation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `confirmation_id` varchar(64) NOT NULL COMMENT '确认业务ID',
  `action` varchar(32) NOT NULL COMMENT '高风险动作编码',
  `draft_id` varchar(64) NOT NULL COMMENT '草稿业务ID',
  `draft_revision` bigint NOT NULL COMMENT '确认绑定的草稿版本',
  `user_id` bigint NOT NULL COMMENT '确认用户强边界',
  `session_id` varchar(64) DEFAULT NULL COMMENT '发起会话，仅审计',
  `input_digest` char(64) NOT NULL COMMENT 'canonical initialInput SHA-256',
  `token_hash` char(64) DEFAULT NULL COMMENT '一次性令牌 SHA-256，不存明文',
  `status` varchar(16) NOT NULL COMMENT 'PENDING|CONFIRMED|CONSUMED|EXPIRED|CANCELLED',
  `expires_at` datetime NOT NULL COMMENT '确认过期时间',
  `confirmed_at` datetime DEFAULT NULL,
  `consumed_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_harness_confirmation_id` (`confirmation_id`),
  UNIQUE KEY `uk_harness_confirmation_action_revision` (`action`, `draft_id`, `draft_revision`),
  KEY `idx_harness_confirmation_token` (`token_hash`),
  KEY `idx_harness_confirmation_expiry` (`status`, `expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Harness高风险动作确认';

CREATE TABLE IF NOT EXISTS `ai_harness_operation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `operation_id` varchar(64) NOT NULL COMMENT '操作业务ID',
  `action` varchar(32) NOT NULL COMMENT '高风险动作编码',
  `draft_id` varchar(64) NOT NULL COMMENT '草稿业务ID',
  `draft_revision` bigint NOT NULL COMMENT '操作绑定的草稿版本',
  `user_id` bigint NOT NULL COMMENT '操作用户强边界',
  `session_id` varchar(64) DEFAULT NULL COMMENT '发起会话，仅审计',
  `input_digest` char(64) NOT NULL COMMENT 'canonical initialInput SHA-256',
  `status` varchar(16) NOT NULL COMMENT 'PENDING|RUNNING|SUCCEEDED|FAILED|UNKNOWN',
  `result_summary_json` longtext DEFAULT NULL COMMENT '脱敏、截断后的安全结果摘要',
  `error_code` varchar(64) DEFAULT NULL COMMENT '稳定错误编码',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '脱敏错误摘要',
  `started_at` datetime DEFAULT NULL,
  `heartbeat_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_harness_operation_id` (`operation_id`),
  UNIQUE KEY `uk_harness_operation_action_revision` (`action`, `draft_id`, `draft_revision`),
  KEY `idx_harness_operation_owner` (`user_id`, `operation_id`),
  KEY `idx_harness_operation_status` (`status`, `heartbeat_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Harness高风险幂等操作';
